---
name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ["3.9", "3.10", "3.11"] #, "3.12"] # TODO: add 3.12 by fixing https://github.com/Deltares/hydromt_delft3dfm/issues/136
        os: ["windows-latest"]

    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          channels: conda-forge
          channel-priority: strict
          environment-file: envs/hydromt-delft3dfm.yml
          activate-environment: hydromt-delft3dfm

      - name: Conda info
        run: |
          conda info
          conda list

      - name: Install hydromt_delft3dfm
        run: |
          flit install --pth-file
          hydromt --models

      - name: Test with pytest
        run: |
          python -m pytest --cov=hydromt_delft3dfm --cov-report xml --cov-report term
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}