---
name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: ["windows-latest"]

    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install hydromt_delft3dfm and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev,test]
          hydromt --models

      - name: list env contents
        run: |
          pip list

      - name: Test with pytest
        run: |
          python -m pytest --cov=hydromt_delft3dfm --cov-report xml --cov-report term

      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
