---
name: test-hydromt-dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        hydromt-version: ['dev']
        python-version: ['313'] # ,'314']
        os: [ubuntu-latest, windows-latest]

    name: hydromt-${{ matrix.hydromt-version }} py-${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ matrix.hydromt-version }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: "v0.67.1"
          environments: ${{ matrix.hydromt-version }}-${{ matrix.python-version }}

      - name: List env contents
        run: |
          pixi list -e ${{ matrix.hydromt-version }}-${{ matrix.python-version }}

      - name: Run tests
        run: |
          pixi run --locked -e ${{ matrix.hydromt-version }}-${{ matrix.python-version }} test-cov

      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
